// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../my-page-info.js")

type Info = GetInfo<{
  file: "routes/mypage/index/info/my-page-info.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../../../../root.js");
}, {
  id: "routes/providers";
  module: typeof import("../../../../providers.js");
}, {
  id: "routes/private-route";
  module: typeof import("../../../../private-route.js");
}, {
  id: "routes/mypage/my-page-layout";
  module: typeof import("../../../my-page-layout.js");
}, {
  id: "routes/mypage/index/my-page-index-layout";
  module: typeof import("../../my-page-index-layout.js");
}, {
  id: "routes/mypage/index/info/my-page-info";
  module: typeof import("../my-page-info.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }, false>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];
}