// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/login/oauth2/code/kakao": {
    params: {};
  };
  "/wedding/:url": {
    params: {
      "url": string;
    };
  };
  "/sample": {
    params: {};
  };
  "/link": {
    params: {};
  };
  "/mypage/wedding": {
    params: {};
  };
  "/mypage/info": {
    params: {};
  };
  "/mypage/wedding/:url": {
    params: {
      "url": string;
    };
  };
  "/editor/:url?": {
    params: {
      "url"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/login/oauth2/code/kakao" | "/wedding/:url" | "/sample" | "/link" | "/mypage/wedding" | "/mypage/info" | "/mypage/wedding/:url" | "/editor/:url?";
  };
  "routes/providers.tsx": {
    id: "routes/providers";
    page: "/" | "/sign-in" | "/login/oauth2/code/kakao" | "/wedding/:url" | "/sample" | "/link" | "/mypage/wedding" | "/mypage/info" | "/mypage/wedding/:url" | "/editor/:url?";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/kakao-redirect.tsx": {
    id: "routes/kakao-redirect";
    page: "/login/oauth2/code/kakao";
  };
  "routes/wedding.tsx": {
    id: "routes/wedding";
    page: "/wedding/:url";
  };
  "routes/sample.tsx": {
    id: "routes/sample";
    page: "/sample";
  };
  "routes/link.tsx": {
    id: "routes/link";
    page: "/link";
  };
  "routes/private-route.tsx": {
    id: "routes/private-route";
    page: "/mypage/wedding" | "/mypage/info" | "/mypage/wedding/:url" | "/editor/:url?";
  };
  "routes/mypage/my-page-layout.tsx": {
    id: "routes/mypage/my-page-layout";
    page: "/mypage/wedding" | "/mypage/info" | "/mypage/wedding/:url";
  };
  "routes/mypage/index/my-page-index-layout.tsx": {
    id: "routes/mypage/index/my-page-index-layout";
    page: "/mypage/wedding" | "/mypage/info";
  };
  "routes/mypage/index/wedding/my-page-wedding.tsx": {
    id: "routes/mypage/index/wedding/my-page-wedding";
    page: "/mypage/wedding";
  };
  "routes/mypage/index/info/my-page-info.tsx": {
    id: "routes/mypage/index/info/my-page-info";
    page: "/mypage/info";
  };
  "routes/mypage/detail/my-page-detail-layout.tsx": {
    id: "routes/mypage/detail/my-page-detail-layout";
    page: "/mypage/wedding/:url";
  };
  "routes/mypage/detail/stat/my-page-stat.tsx": {
    id: "routes/mypage/detail/stat/my-page-stat";
    page: "/mypage/wedding/:url";
  };
  "routes/editor.tsx": {
    id: "routes/editor";
    page: "/editor/:url?";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/providers": typeof import("./app/routes/providers.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/sign-in": typeof import("./app/routes/sign-in.tsx");
  "routes/kakao-redirect": typeof import("./app/routes/kakao-redirect.tsx");
  "routes/wedding": typeof import("./app/routes/wedding.tsx");
  "routes/sample": typeof import("./app/routes/sample.tsx");
  "routes/link": typeof import("./app/routes/link.tsx");
  "routes/private-route": typeof import("./app/routes/private-route.tsx");
  "routes/mypage/my-page-layout": typeof import("./app/routes/mypage/my-page-layout.tsx");
  "routes/mypage/index/my-page-index-layout": typeof import("./app/routes/mypage/index/my-page-index-layout.tsx");
  "routes/mypage/index/wedding/my-page-wedding": typeof import("./app/routes/mypage/index/wedding/my-page-wedding.tsx");
  "routes/mypage/index/info/my-page-info": typeof import("./app/routes/mypage/index/info/my-page-info.tsx");
  "routes/mypage/detail/my-page-detail-layout": typeof import("./app/routes/mypage/detail/my-page-detail-layout.tsx");
  "routes/mypage/detail/stat/my-page-stat": typeof import("./app/routes/mypage/detail/stat/my-page-stat.tsx");
  "routes/editor": typeof import("./app/routes/editor.tsx");
};